<h1 style='text-align: center'> SEAL Data Scientist Technical Test </h1>
<h3 style='text-align: center; font-style: italic'> Oleh: Garudapaksi Yusuf </h3>

---

# Buat Tabel

* *Source* data dan instruksi: [Google Drive](https://drive.google.com/drive/folders/16e052sYcXIIhrOVQJ86G_S12SGqrlp96?usp=sharing).
* *Disadur dari `Data Scientist Techncial Test.xlsx` yang tersedia pada folder `docs` dari repository ini dengan sedikit modifikasi untuk memudahkan pemahaman.*

> Buatlah *table* seperti berikut dari data dinas sosial dan data *master* desa:

In [ ]:
# Import library yang dibutuhkan untuk mengakses contoh tabel
import pandas as pd

# Mengakses contoh tabel yang tersedia dalam format 'excel'
contoh_tabel = pd.read_excel(
    io='../docs/Data Scientist Techncial Test.xlsx', # Letak dan nama file dari contoh tabel
    sheet_name='bentuk table', # Nama sheet dari contoh tabel
    index_col='id' # Menggunakan kolom 'id' sebagai index dari contoh tabel
                   # Untuk menghilangkan redundansi dari index yang disediakan secara built-in oleh library Pandas
                   # Dengan 'id' yang berasal dari contoh tabel dengan fungsi yang serupa
)

# Menampilkan 'n' baris pertama dari contoh tabel untuk 'ease of viewing'
contoh_tabel.head(
    n=5
)

,kode_provinsi_y,nama_provinsi,kode_kabupaten_kota,kabupaten,nama_kabupaten_kota,bps_kode_kecamatan,kecamatan,bps_nama_kecamatan,bps_kode_desa_kelurahan,kelurahan,...,kemendagri_nama_desa_kelurahan,periode_update,nik,nama,alamat,kategori,kategori.1,jumlah,satuan,tahun
id,,,,,,,,,,,,,,,,,,,,,
1,35,JAWA TIMUR,3526,KABUPATEN BANGKALAN,KABUPATEN BANGKALAN,3526140,GEGER,GEGER,3526140002,LERPAK,...,LERPAK,TRIWULAN I 2024,3526060000000000,ABD HALIM,DSN GLIMBUR,NaN,-,-,-,2024
2,35,JAWA TIMUR,3526,KABUPATEN BANGKALAN,KABUPATEN BANGKALAN,3526070,GALIS,GALIS,3526070004,GALIS,...,GALIS,TRIWULAN I 2024,3526180000000000,ABD. ROHMAN,DSN. REMBAH GALIS,NaN,-,-,-,2024
3,35,JAWA TIMUR,3526,KABUPATEN BANGKALAN,KABUPATEN BANGKALAN,3526070,GALIS,GALIS,3526070009,LONGKEK,...,LONGKEK,TRIWULAN I 2024,3526190000000000,ABDUS SYUKUR,DSN. BARAT SUMBER,NaN,-,-,-,2024
4,35,JAWA TIMUR,3526,KABUPATEN BANGKALAN,KABUPATEN BANGKALAN,3526140,GEGER,GEGER,3526140006,CAMPOR,...,CAMPOR,TRIWULAN I 2024,3526060000000000,ACHMAD,DSN POCONG,NaN,-,-,-,2024
5,35,JAWA TIMUR,3526,KABUPATEN BANGKALAN,KABUPATEN BANGKALAN,3526090,TRAGAH,TRAGAH,3526090013,TRAGAH,...,TRAGAH,TRIWULAN I 2024,3526140000000000,ACHMAD RIDOI,DSN. BANGGUMOK,NaN,-,-,-,2024

> *Note*: untuk *header* kolom menggunakan bentuk kecil semua dan isi data mengguanakan huruf besar semua.

Berikutnya, contoh tabel di atas akan dibandingkan dengan data dinas sosial dan data *master* desa yang tersedia pada folder `data`.

In [55]:
# Membuat variabel instances dari data dinas sosial dalam format 'csv'
dinsos_csv = pd.read_csv(
    filepath_or_buffer='../data/Data Dinas Sosial.csv',
    sep=';', # Character yang digunakan sebagai delimiter/separator
    index_col='id'
)

# Dan dalam format 'excel'
dinsos_xlsx = pd.read_excel(
    io='../data/Data Dinas Sosial.xlsx',
    index_col='id'
)

# Membuat variabel instance dari data master desa
master_desa = pd.read_csv(
    filepath_or_buffer='../data/masterdesa.csv',
    sep=';'
)

In [ ]:
# Menampilkan 5 baris pertama dari 'Data Dinas Sosial.csv'
dinsos_csv.head(
    n=5
)

,kode_provinsi,nama_provinsi,periode_update,nik,nama,alamat,provinsi,kabupaten,kecamatan,kelurahan,tahun,kategori,jumlah,satuan
id,,,,,,,,,,,,,,
1,35,Jawa Timur,Triwulan I 2024,"3,52606E+15",ABD HALIM,DSN GLIMBUR,JAWA TIMUR,KAB. BANGKALAN,GEGER,LERPAK,2024,-,-,-
2,35,Jawa Timur,Triwulan I 2024,"3,52618E+15",ABD. ROHMAN,DSN. REMBAH GALIS,JAWA TIMUR,KAB. BANGKALAN,GALIS,GALIS,2024,-,-,-
3,35,Jawa Timur,Triwulan I 2024,"3,52619E+15",ABDUS SYUKUR,DSN. BARAT SUMBER,JAWA TIMUR,KAB. BANGKALAN,GALIS,LONGKEK,2024,-,-,-
4,35,Jawa Timur,Triwulan I 2024,"3,52606E+15",ACHMAD,DSN POCONG,JAWA TIMUR,KAB. BANGKALAN,GEGER,CAMPOR,2024,-,-,-
5,35,Jawa Timur,Triwulan I 2024,"3,52614E+15",ACHMAD RIDOI,DSN. BANGGUMOK,JAWA TIMUR,KAB. BANGKALAN,TRAGAH,TRAGAH,2024,-,-,-

In [ ]:
# Menampilkan 5 baris pertama dari 'Data Dinas Sosial.xlsx'
dinsos_xlsx.head(
    n=5
)

,kode_provinsi,nama_provinsi,periode_update,nik,nama,alamat,provinsi,kabupaten,kecamatan,kelurahan,tahun,kategori,jumlah,satuan
id,,,,,,,,,,,,,,
1,35,Jawa Timur,Triwulan I 2024,352606000000000000000,ABD HALIM,DSN GLIMBUR,JAWA TIMUR,KAB. BANGKALAN,GEGER,LERPAK,2024,-,-,-
2,35,Jawa Timur,Triwulan I 2024,352618000000000000000,ABD. ROHMAN,DSN. REMBAH GALIS,JAWA TIMUR,KAB. BANGKALAN,GALIS,GALIS,2024,-,-,-
3,35,Jawa Timur,Triwulan I 2024,352619000000000032768,ABDUS SYUKUR,DSN. BARAT SUMBER,JAWA TIMUR,KAB. BANGKALAN,GALIS,LONGKEK,2024,-,-,-
4,35,Jawa Timur,Triwulan I 2024,352606000000000000000,ACHMAD,DSN POCONG,JAWA TIMUR,KAB. BANGKALAN,GEGER,CAMPOR,2024,-,-,-
5,35,Jawa Timur,Triwulan I 2024,352614000000000000000,ACHMAD RIDOI,DSN. BANGGUMOK,JAWA TIMUR,KAB. BANGKALAN,TRAGAH,TRAGAH,2024,-,-,-

In [ ]:
# Menampilkan 5 baris pertama dari data master desa
master_desa.head(
    n=5
)

,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,bps_kode_kecamatan,bps_nama_kecamatan,bps_kode_desa_kelurahan,bps_desa_kelurahan,kemendagri_kode_kecamatan,kemendagri_nama_kecamatan,kemendagri_kode_desa_kelurahan,kemendagri_desa_kelurahan
0,35,JAWA TIMUR,3501,KABUPATEN PACITAN,3501010,DONOROJO,3501010001,WIDORO,35.01.01,DONOROJO,35.01.01.2001,WIDORO
1,35,JAWA TIMUR,3501,KABUPATEN PACITAN,3501010,DONOROJO,3501010002,SAWAHAN,35.01.01,DONOROJO,35.01.01.2002,SAWAHAN
2,35,JAWA TIMUR,3501,KABUPATEN PACITAN,3501010,DONOROJO,3501010003,KALAK,35.01.01,DONOROJO,35.01.01.2003,KALAK
3,35,JAWA TIMUR,3501,KABUPATEN PACITAN,3501010,DONOROJO,3501010004,SENDANG,35.01.01,DONOROJO,35.01.01.2004,SENDANG
4,35,JAWA TIMUR,3501,KABUPATEN PACITAN,3501010,DONOROJO,3501010005,KLEPU,35.01.01,DONOROJO,35.01.01.2005,KLEPU

> Lakukan *check* pada data tersebut apakah ada kolom nilai *null* atau tidak. Jika ada nilai null lakukan cleansing data pada table yang sudah dilakukan join sehingga meminimalisir nilai null. Buatlah coding cleansing dengan bahasa python. Asumsikan akan melakukan cleansing data pada data yang jumlahnya besar dan beragam sehingga buatlah algoritma coding yang bisa digunakan untuk banyak case data.